stages:
  - build

# 定义 job
mvndeploy:
  stage: build
  only:
    - develop
    - master
  script:
    # 编译前端项目；
    - cd app-contracts/ui/web
    - npm install
    - npm run build
    - cd ../../
    - echo Completed building of the ui projects!
    - ls ui/web/dist
    # 编译打包后端项目；
    - mvn clean package
    - cd ..

  cache:
    paths:
      - app-contracts/ui/web/node_modules/

